name: CI

on:
  merge_group:
    types: [checks_requested]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "website/**"
    tags-ignore:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

permissions:
  # Allow commenting on issues for `reusable-build.yml`
  issues: write

env:
  RUNNER_LABEL: ${{ vars.runner_label || '"ubuntu-22.04"' }}

jobs:
  test:
    strategy:
      matrix:
        os:
          - ${{ env.RUNNER_LABEL }}
    runs-on: ${{ fromJSON(matrix.os) }}
#    runs-on: ubuntu-22.04
#    runs-on: ${{ fromJSON(vars.runner_label || '"ubuntu-22.04"') }}
    steps:
      - name: Test
        run: |
          echo "$RUNNER_LABEL"
