name: Get Runner Labels

on:
  workflow_call:
    inputs:
      force-use-github-runner:
        type: boolean
        description: "Force use github runner"
        required: false
        default: false
    outputs:
      LINUX_RUNNER_LABELS:
        description: "linux runner labels"
        value: ${{ jobs.main.outputs.LINUX_RUNNER_LABELS }}
      MACOS_RUNNER_LABELS:
        description: "macos runner labels"
        value: ${{ jobs.main.outputs.MACOS_RUNNER_LABELS }}
      WINDOWS_RUNNER_LABELS:
        description: "windows runner labels"
        value: ${{ jobs.main.outputs.WINDOWS_RUNNER_LABELS }}

jobs:
  main:
    name: Get Runner Labels
    runs-on: [self-hosted, Linux]
    outputs:
      LINUX_RUNNER_LABELS: ${{ steps.run.outputs.LINUX_RUNNER_LABELS }}
      MACOS_RUNNER_LABELS: ${{ steps.run.outputs.MACOS_RUNNER_LABELS }}
      WINDOWS_RUNNER_LABELS: ${{ steps.run.outputs.WINDOWS_RUNNER_LABELS }}
    steps:
      - id: run
        shell: bash
        env:
          TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "aaa$TOKEN"
          if [[ "$TOKEN" = "ads" ]]; then
             echo "hahah"
          fi
