name: Release Canary

on:
  workflow_dispatch:
    inputs:
      commit:
        required: true
        type: string
        description: "Commit SHA"
      test:
        required: false
        type: boolean
        default: false
        description: "Run tests"
      profile:
        required: true
        type: choice
        default: release
        options:
          - release
          - profiling
          - ci
        description: "profiling means release with debug info for profiling, ci means release with debug info and faster build time"

permissions:
  # To publish packages with provenance
  id-token: write
  # Allow commenting on issues for `reusable-build.yml`
  issues: write

env:
  TEST_RUNNER_NAME: ${{ vars.test || "ubuntu-22.04" }}

jobs:
  test:
    name: Get Runner Labels
    run: |
      echo "$TEST_RUNNER_NAME"
